In [5]:
import math
def basic_sigmoid(x):
    x = 1/(1+math.exp(-x))
    return x

print(basic_sigmoid(3))

0.9525741268224334


In [2]:
import numpy as np
x = np.array([1,2,3])
print(np.exp(x))

[  2.71828183   7.3890561   20.08553692]


In [6]:
def sigmoid(x):
    x = 1./(1.+np.exp(-x))
    return x
x = np.array([1,2,3])
print(sigmoid(x))

[ 0.73105858  0.88079708  0.95257413]


In [11]:
def sigmoid_derivative(x):
    s = sigmoid(x)
    dx = s * (1-s)
    return dx

In [12]:
x = np.array([1,2,3])
print(sigmoid(x))
print(sigmoid_derivative(x))

[ 0.73105858  0.88079708  0.95257413]
[ 0.19661193  0.10499359  0.04517666]


In [16]:
def image2vector(image):
    v = image.reshape((image.shape[0]*image.shape[1]*image.shape[2],1))
    return v

In [17]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[ 0.67826139]
 [ 0.29380381]
 [ 0.90714982]
 [ 0.52835647]
 [ 0.4215251 ]
 [ 0.45017551]
 [ 0.92814219]
 [ 0.96677647]
 [ 0.85304703]
 [ 0.52351845]
 [ 0.19981397]
 [ 0.27417313]
 [ 0.60659855]
 [ 0.00533165]
 [ 0.10820313]
 [ 0.49978937]
 [ 0.34144279]
 [ 0.94630077]]


In [19]:
def normalizeRows(x):
    x_norm = np.linalg.norm(x,axis=1,keepdims=True)
    x = x/x_norm
    return x

In [20]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[ 0.          0.6         0.8       ]
 [ 0.13736056  0.82416338  0.54944226]]


In [23]:
def softmax(x):
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis = 1, keepdims = True)
    s = x_exp / x_sum
    return s

In [24]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[  9.80897665e-01   8.94462891e-04   1.79657674e-02   1.21052389e-04
    1.21052389e-04]
 [  8.78679856e-01   1.18916387e-01   8.01252314e-04   8.01252314e-04
    8.01252314e-04]]


In [3]:
def L1(yhat, y):
    loss = np.sum(np.absolute(y-yhat))
    return loss

In [4]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


In [7]:
def L2(yhat, y):
    loss = np.sum(np.power(y - yhat,2))
    return loss

In [8]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43
